services:
  - type: web
    name: api-node-products
    runtime: node
    rootDir: Api-Node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
  - type: web
    name: api-springboot-products
    runtime: docker
    rootDir: Api-SpringBoot
    dockerfilePath: ./Dockerfile
    dockerContext: .
  - type: web
    name: api-django-products
    runtime: python
    rootDir: Api-Django
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
